// AUTO-GENERATED by scripts/sync-projects.mjs — do not edit manually
// Run: node scripts/sync-projects.mjs to regenerate

export interface ProjectMeta {
  slug: string;
  title: string;
  tags: string[];
  stack: string[];
  stats: { label: string; value: string }[];
  cover: string;
}

export const PROJECTS: ProjectMeta[] = [
  {
    "slug": "epaper-subscription",
    "title": "ePaper Subscription Platform",
    "tags": [
      "Digital Transformation",
      "Publishing",
      "UX"
    ],
    "stack": [
      "React",
      "Node.js",
      "PostgreSQL"
    ],
    "stats": [],
    "cover": "cover.png"
  },
  {
    "slug": "growfast",
    "title": "GrowFast → ET Masterclasses",
    "tags": [
      "Growth",
      "EdTech",
      "Product Strategy"
    ],
    "stack": [
      "Figma",
      "Analytics",
      "A/B Testing"
    ],
    "stats": [
      {
        "label": "Revenue Growth",
        "value": "2.3×"
      },
      {
        "label": "User Retention",
        "value": "+42%"
      }
    ],
    "cover": "cover.png"
  },
  {
    "slug": "project-kronos",
    "title": "Project Kronos",
    "tags": [],
    "stack": [],
    "stats": [],
    "cover": ""
  }
] as const;
